<?xml version="1.0"?>
<package format="3">
  <name>unitree_movegroup_interface</name>
  <version>0.0.1</version>
  <description>MoveIt2 Move Group Interface Tutorial</description>
  <maintainer email="jankech@robotecvhvision.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>graph_msgs</depend>
  <depend>moveit_visual_tools</depend>
</package>
