# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - left_wrist_roll_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    constraints:
      goal_time: 10.0
      stopped_velocity_tolerance: 1000.0  # ignoring velocity tolerance (TODO: check if velocity state bug occurs only in simulation)
      goal:
        waist_yaw_joint: 0.02
        waist_roll_joint: 0.02
        waist_pitch_joint: 0.02
        right_shoulder_pitch_joint: 0.02
        right_shoulder_roll_joint: 0.02
        right_shoulder_yaw_joint: 0.02
        right_elbow_joint: 0.02
        right_wrist_roll_joint: 0.02
        right_wrist_pitch_joint: 0.02
        right_wrist_yaw_joint: 0.02
    joints:
      - waist_yaw_joint
      - waist_roll_joint
      - waist_pitch_joint
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint
      - right_wrist_roll_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint
    gains:
      # TODO: antiwindup
      waist_yaw_joint: {p: 1.0, i: 0.5, d: 0.015, i_clamp: 0.5}
      waist_roll_joint: {p: 1.0, i: 1.0, d: 0.015, i_clamp: 0.5}
      waist_pitch_joint: {p: 1.0, i: 1.0, d: 0.015, i_clamp: 0.5}
      right_shoulder_pitch_joint: {p: 1.0, i: 2.0, d: 0.015, i_clamp: 0.5}
      right_shoulder_roll_joint: {p: 1.0, i: 2.0, d: 0.015, i_clamp: 0.5}
      right_shoulder_yaw_joint: {p: 1.0, i: 2.0, d: 0.015, i_clamp: 0.5}
      right_elbow_joint: {p: 1.0, i: 2.0, d: 0.015, i_clamp: 0.5}
      right_wrist_roll_joint: {p: 1.0, i: 2.0, d: 0.015, i_clamp: 0.5}
      right_wrist_pitch_joint: {p: 1.0, i: 2.0, d: 0.015, i_clamp: 0.5}
      right_wrist_yaw_joint: {p: 1.0, i: 2.0, d: 0.015, i_clamp: 0.5}
    command_interfaces:
      - position
      - effort
    state_interfaces:
      - position
      - velocity
left_hand_controller:
  ros__parameters:
    joints:
      - left_index_1_joint
      - left_little_1_joint
      - left_middle_1_joint
      - left_ring_1_joint
      - left_thumb_1_joint
      - left_thumb_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
right_hand_controller:
  ros__parameters:
    joints:
      - right_index_1_joint
      - right_little_1_joint
      - right_middle_1_joint
      - right_ring_1_joint
      - right_thumb_1_joint
      - right_thumb_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort